apiVersion: v1
kind: Pod
metadata:
  name: foobar
spec:
  containers:
  - name: foo
    image: alpine:latest
    resources:
        limits:
          memory: 10Mi
          cpu: 100m
    command:
      - top