apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: foobar
spec:
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
        containers:
        - name: foo
          image: foobar:python
          ports:
            - containerPort: 5000
